package com.ntu.timetabling.model;

public enum RoomLayout {
    NONE,
    OFFSITE,
    COLLABORATIVE,
    IT,
    RESTRICTED_STUDIO,
    ROWS,
    RESTRICTED_OTHER,
    RESTRICTED_IT,
    TIERED_FIXED_ROWS,
    GROUP_TECHNOLOGY,
    SMALL_GROUP,
    FLAT_FIXED_ROWS,
    RESTRICTED_LABORATORY,
    SCALE_UP,
    HORSESHOE,
    TERCO_GROUP_TECHNOLOGY,
    RESTRICTED_WORKSHOP,
    HYFLEARNING,
    INDEPENDENT_MS_TEAMS_LINK
}
